ChorusOne/solido

program/tests/tests/solana_assumptions.rs
=> Update comment with stake difference explanation

program/src/processor.rs, program/tests/tests/withdrawals.rs
Closes #336.
The change to the program is fairly small, but in order to test it, I refactored the withdrawal tests a bit so there is a shared setup part that can be reused by multiple tests.
=> Limit withdrawal amount per withdrawal to 10% of the validator balance

etc/grafana-dashboard.json
This might be useful to others too. This is what it looks like for the testnet deployment:
=> Add json for Solido Grafana dashboard

cli/src/helpers.rs
Also align the metrics. New output:
```
Metrics:
Total treasury fee:       0.000000000 stSOL, valued at 0.000000000 SOL when it was paid
Total validation fee:     0.000000000 stSOL, valued at 0.000000000 SOL when it was paid
Total developer fee:      0.000000000 stSOL, valued at 0.000000000 SOL when it was paid
Total stSOL appreciation: 0.000000000 SOL
Total deposited:          10.000000000 SOL
Number of deposits ≤           0.000100000 SOL: 0
Number of deposits ≤           0.001000000 SOL: 0
Number of deposits ≤           0.010000000 SOL: 0
Number of deposits ≤           0.100000000 SOL: 0
Number of deposits ≤           1.000000000 SOL: 0
Number of deposits ≤          10.000000000 SOL: 1
Number of deposits ≤         100.000000000 SOL: 1
Number of deposits ≤        1000.000000000 SOL: 1 …
```
=> Print validator unstake details in `solido show-solido`

program/src/processor.rs
Addresses the comments I left in https://github.com/ChorusOne/solido/pull/393#pullrequestreview-742356493.
To do:
=> Tweak withdraw from unstake

CHANGELOG.md
Updated change log with point fix for maintainer
=> Added maintainer least balance fix to changelog

program/tests/context.rs, program/tests/tests/add_remove_validator.rs, program/tests/tests/collect_validator_fee.rs, program/tests/tests/solana_assumptions.rs
Test that only the withdraw authority can change the commission.
Closes #412.
=> Test commission change.

cli/src/maintenance.rs
This enables two things:
* We no longer assume that the configured signer is a maintainer, so you can run the maintenance daemon even if your account does not exist on mainnet. It will never perform any maintenance (after we implement duties), but you can still extract metrics this way.
* Maintainers (or anybody really) can monitor each other, not just themselves.
=> Include balances of all maintainers in metrics

cli/src/maintenance.rs
Fixes https://github.com/ChorusOne/solido/issues/429.
=> Expose more validator stats in metrics

Cargo.lock, anker/Cargo.toml, anker/src/instruction.rs, anker/src/logic.rs, anker/src/processor.rs, anker/src/state.rs, anker/src/token.rs, anker/tests/tests/deposit.rs, anker/tests/tests/mod.rs, anker/tests/tests/withdraw.rs, testlib/src/anker_context.rs
Implements the final part of #444. Resolves #453 by picking the most pessimistic exchange rate upon withdraw.
To do:
=> Implement withdraw in Anker

anker/SECURITY.md
I wrote up how the program is supposed to work, and who we trust, to help auditors, and future bounty hunters. (Right now the Anker program is not yet in scope for the bug bounty.)
=> Add Anker audit guide / security document

anker/src/instruction.rs, anker/src/logic.rs, anker/src/processor.rs, anker/src/state.rs, anker/tests/tests/amm.rs, anker/tests/tests/manager.rs, anker/tests/tests/mod.rs, anker/tests/tests/sell_rewards.rs, testlib/src/anker_context.rs
Manager functions to change the Token Swap pool instance and the Terra rewards destination.
Test both functions
=> [Anker] Manager functions

Cargo.lock, anker/Cargo.toml, anker/src/error.rs, anker/src/instruction.rs, anker/src/lib.rs, anker/src/processor.rs, anker/src/state.rs, anker/src/wormhole.rs, anker/tests/tests/manager.rs, cli/src/commands_anker.rs, cli/src/config.rs, testlib/src/anker_context.rs, tests/test_anker.py
Implement Wormhole instruction to send UST tokens to the Terra chain.
It was difficult to include the wormhole project. This rewrites some code from their repository.
~I don't understand the `nonce` and `fee` parameters. We should figure out if these are malleable before approving this PR.~
Fee should be set to 0: that's the fee payed in form of the transferred token in the target chain, to incentivize relayers.
Nonce is a random number, used to differentiate transactions with the same parameter, this is set by the caller.
We can leave implementing tests in a later PR, as this is already extensive.
Closes #445, #470
Review carefully 🕵️
=> [Anker] Send UST tokens via wormhole.

anker/src/instruction.rs, anker/src/lib.rs, anker/src/logic.rs, anker/src/metrics.rs, anker/src/processor.rs, anker/src/state.rs, anker/tests/tests/sell_rewards.rs
Log the total number of StSOL and UST sold by the `SellRewards`
function.
Add some logging and tests.
=> [Anker] Add metrics

.github/workflows/build.yml, .github/workflows/nightly.yml, buildimage.sh, docker/Dockerfile.dev, tests/util.py
Tests were failing for Solana SDK 1.7.8. Updating it to 1.7.15 seems to fix the problem.
=> Upgrade Solana to 1.7.15

cli/src/commands_anker.rs, cli/src/config.rs, tests/test_anker.py, tests/test_solido.py
Create the token pool instance from the client, used for testing purposes only.
=> Create token pool instance

anker/src/logic.rs
=> Avoid expensive prints in Anker::Initialize

cli/src/commands_anker.rs, cli/src/config.rs, tests/test_anker.py
Depends on #497.
* Add a new CLI command, `solido anker withdraw`.
* Test it in `test_anker.py`.
=> Add `solido anker withdraw` command, add test for it

cli/listener/src/main.rs
I wanted to test some changes in the server part, but have it run against an existing database that a different instance of the daemon is already writing to. So add a read-only mode (`--fetch disable`) that runs only the http server part and not the fetch-prices-from-the-chain part.
I would have liked to have `--fetch` and `--no-fetch` flags instead, but I don’t know how to do this with Clap `#[derive]` macros. I found some discussions about it with workarounds that use the method-chaining builders. So for now let’s make it an option instead.
=> Add readonly mode to APY daemon

anker/src/processor.rs, anker/src/state.rs
Make some tests for later use on slippage
=> Add type/methods for `HistoricalStSolPriceArray`

anker/src/error.rs, anker/src/instruction.rs, anker/src/logic.rs, anker/src/processor.rs, anker/src/state.rs, anker/tests/tests/sell_rewards.rs, testlib/src/anker_context.rs, tests/test_anker.py
=> Add minimum amount for slippage

anker/tests/tests/fetch_pool_price.rs, anker/tests/tests/mod.rs
Add some tests for the `FetchPoolPrice` instruction.
=> Test fetch pool price

cli/maintainer/src/commands_anker.rs, cli/maintainer/src/config.rs
Add functions to:
- Change Terra rewards destination
- Change token swap pool
- Change `sell_rewards_min_bps`
=> Add maintainer functions for Anker

cli/common/src/prometheus.rs, cli/maintainer/src/config.rs, cli/maintainer/src/maintenance.rs
Write Anker metrics to prometheus so we can observe deposits/withdrawals
Closes #450
=> Write Anker metrics to prometheus

cli/maintainer/src/maintenance.rs
Track:
- Total minted bSOL.
- stSOL in reserve.
- UST in reserve.
=> Add metrics for reserve

CHANGELOG.md, Cargo.lock, anker/Cargo.toml, cli/common/Cargo.toml, cli/listener/Cargo.toml, cli/listener/fuzz/Cargo.lock, cli/maintainer/Cargo.toml, program/Cargo.toml
Also bump the version in the Cargo.toml files.
=> Add changelog for v1.3.2

js/src/instructions/withdraw.ts
First account should be solido instance instead of solido program
=> Fix: getWithdrawInstruction

cli/maintainer/src/maintenance.rs
Closes #578
Sum inactive stake on stake and unstake accounts.
Use deactivating stake on `unstake_accounts`.
Please confirm that these are the combinations allowed here
=> Expose deactivating stake
