ChorusOne/solido

- codecov.yml
I think this creates more noise than that it is helpful in most cases, let’s disable it.
Reference: https://docs.codecov.com/docs/pull-request-comments#disable-comment
> Prevent Codecov bot from commenting on pull requests

- .github/workflows/nightly.yml
The nightly build and test now made it through the Solido tests, but in the second airdrop of the second airdrop round, it failed again on rate limits. Slow down even more, so hopefully we make it through this round of airdrops too.
> Rate limit airdrops in nightly tests even more

- cli/src/config.rs
- cli/src/daemon.rs
- cli/src/helpers.rs
- cli/src/main.rs
- cli/src/multisig.rs
- cli/src/spl_token_utils.rs
- program/src/balance.rs
- program/src/error.rs
- program/src/logic.rs
- program/src/process_management.rs
- program/src/processor.rs
- program/src/token.rs
Just as the `Deposit` instruction has a client-side implementation, this PR implements the client-side for `Withdraw`.
It's mainly useful for testing, as withdrawals will be done in the browser UI.
> Implement `Withdraw` in the client.

- .github/workflows/build.yml
- tests/airdrop_lamports.sh
Our tests are failing because sometimes the airdrop fails. This PR tries to mitigate this by retrying and waiting some time in-between.
Closes #342
> Airdrops more times in case of error.

- cli/src/config.rs
- cli/src/helpers.rs
- cli/src/main.rs
- program/src/error.rs
- program/src/logic.rs
- program/src/processor.rs
- tests/test_solido.py
Adds the possibility of specifying the minter and Solido keys for the Solido initialization. Also creates the command `show-authorities` to show the Solido authorities given a known public key. When initializing the Solido instance with an existing key, the initialization step changes slightly. Now it is also required to make a new private key for the Solido instance and pass it in the initialization method.
Adds extra check for the mint, now we require that the mint has the Solido authority for minting and hasn't minted any tokens yet (supply is zero).
> Specify mint and Solido keys.

- .github/workflows/build.yml
- README.md
- docker/Dockerfile.maintainer
- docker/LICENSE
- tests/check_licenses.py
Closes #120.
* Add a CI step to check that we don’t accidentally introduce dependencies on libraries with incompatible licenses.
* Include a `LICENSE` and `LICENSE-DEPENDENCIES` file in the container image that we redistribute. The file `LICENSE-DEPENDENCIES` then contains a list of dependencies grouped by [SPDX license identifier](https://spdx.org/licenses/). Most of these licenses are included in the container image, because it’s based on Debian, which includes those licenses:
```
$ ls /usr/share/common-licenses/
Apache-2.0  Artistic  BSD  CC0-1.0  GFDL  GFDL-1.2  GFDL-1.3  GPL  GPL-1  GPL-2  GPL-3  LGPL  LGPL-2  LGPL-2.1  LGPL-3  MPL-1.1  MPL-2.0
```
These are not all of the licenses used by our dependencies though. I realize that Wenger & Vieli recommended to include the full text, …
> Add more license details

- .github/workflows/build.yml
- README.md
- cli/src/error.rs
- cli/src/main.rs
- docker/Dockerfile.maintainer
- docker/LICENSE
- tests/check_licenses.py
We just ran into this while testing on testnet, where the RPC returned an error, but the transaction did execute. Add a warning for this particular error, to point this out to the user. I don't know if there are other cases where a transaction may have executed though, should we always warn?
> Warn that transactions may have executed on error

- cli/src/error.rs
- cli/src/main.rs
- cli/src/multisig.rs
- tests/test_multisig.py
Previously `multisig approve` and `multisig execute-transaction` would not print anything. Now they print the Solana transaction id, so you can look it up in a block explorer. `approve` also prints how many approvals the transaction has afterwards, so you know immediately if you can execute it.
While testing this, I ran into the RPC returning `InstructionError(0, Custom(105))`, which is not particularly helpful, so I also extended the error reporting to try and convert this back to a Solido error or Multisig error. Unfortunately there seems to be a bug in Anchor, that prevents converting back from an error code to the structured error. But at least for Solido we should now get more details.
Previous output:
```
Solana RPC client returned an error:
Request:    Some(SendTransaction)
Kind: …
```
> Improve multisig user experience for `approve` and `execute`, improve error reporting

- README.md
I think docs on how to build make more sense to have in the repository itself than in the hosted docs, let’s move that here.
> Extend readme, move build docs here

- program/src/instruction.rs
I went through all the accounts and added comments against the is_writable fields to hopefully make it easier to reason about why the said accounts are writable.  
Additionally set the stake_authority.is_writable : false in StakeDepositAccounts as per original comment on #222
> 222 check writable attributes from instructions

- Cargo.lock
- cli/Cargo.toml
- cli/src/main.rs
With #343, we added support for `?key=` derivation paths in `usb://ledger` keypair paths, but I broke support for the bare `usb://ledger` path. This should fix that, and it adds a test to ensure that we can parse both.
@fkbenjamin, can you check whether you can use the `usb://ledger` path again with this version?
> Fix support for usb://ledger keypair path without ?key query param

- cli/src/error.rs
- cli/src/main.rs
In particular, add a hint about the Ledger "blind signing" setting, to make the error a bit more actionable for the user.
@enriquefynn I don’t have a Ledger at hand at the moment, can you verify that this prints the right hint when the "blind signing" setting is disabled?
> Pretty-print `SignerError`s

- cli/src/config.rs
- cli/src/helpers.rs
- cli/src/maintenance.rs
- cli/src/multisig.rs
- program/src/balance.rs
- program/src/error.rs
- program/src/instruction.rs
- program/src/process_management.rs
- program/src/processor.rs
- program/src/state.rs
- program/tests/context.rs
- tests/test_solido.py
Steps towards validator's removal #347.
Replaces the validator's weight with the boolean flag `active`.
When the `active` flag is `false`, the validator cannot receive stake deposits. The maintenance bot should also ignore inactive validators and not try to stake more Sol to them.
> Active flag

- cli/src/config.rs
- cli/src/multisig.rs
- program/tests/tests/withdrawals.rs
- tests/prepare_test_environment.py
- tests/test_multisig.py
- tests/test_solido.py
- tests/util.py
Add a new subcommand `token` to the multisig subcommand. In the future we may support more token instructions, e.g., burning, creating. For now we support only token transfers.
Note: when doing just the `multisig token` params, there's a clap error: "`Option::unwrap()` on a `None` value".
I'm still verifying what can be done, but it works well with the `--help` flag. 🤷 
Closes #320
> Add token transfer to the client.

- cli/src/error.rs
- tests/test_multisig.py
#177 was starting to bug me, “fix” it. This is a bit of an ugly fix; the bug is in Anchor and it really should be fixed there ([this turned out to be the problem](https://github.com/project-serum/anchor/pull/354#issuecomment-897717786)), but until then, we can work around it here.
> Fix parsing of multisig errors

- CHANGELOG.md
- cli/src/config.rs
I noticed while reviewing our deployment of the maintainer that the listen address is a positional argument rather than one with a long-form flag. I think this was an oversight, make it `--listen` instead.
> Make listen an option to run-maintainer

- program/src/instruction.rs
- program/src/process_management.rs
- program/src/processor.rs
- program/tests/context.rs
- program/tests/tests/add_remove_validator.rs
- program/tests/tests/stake_deposit.rs
This implements part 1 of #364: adding a `Deactivate` instruction.
I will open a follow-up pull request to allow proposing a multisig transaction for this.
> Add `Deactivate` instruction

- program/src/processor.rs
Brian mentioned this morning that he did a deposit on devnet, and it worked, but transaction on explorer.solana.com is difficult to
understand. Part of this is just inherent, we need to reference all of those accounts. The way to make this more comprehensible is for block explorers to add special Solido parsers. But there is one thing we can do on our side: log what we did.
> Log what we did from deposit and withdraw

- cli/src/config.rs
- cli/src/helpers.rs
- cli/src/main.rs
- cli/src/multisig.rs
- tests/test_solido.py
This is a follow-up to #370 and implements the final part of #364:
* Add support for the `Deactivate` instruction in `solido multisig show-transaction`.
* Add `solido deactivate-validator` to propose a `Deactivate` to the multisig.
* Test it in `test_solido.py`.
* As a drive-by fix, fix some of the command descriptions.
> Add `solido deactivate-validator` subcommand

- program/src/stake_account.rs
- program/tests/tests/solana_assumptions.rs
Previously, `StakeAccount` was wrong, it displayed the number of active Lamports even when some Lamports were deactivating. This adds some tests to safeguard changes in Solana.
> Test `StakeAccount` and bugfix.

- cli/src/helpers.rs
- cli/src/maintenance.rs
- docker/Dockerfile.dev
- program/src/error.rs
- program/src/instruction.rs
- program/src/lib.rs
- program/src/logic.rs
- program/src/process_management.rs
- program/src/processor.rs
- program/src/stake_account.rs
- program/src/state.rs
- program/tests/context.rs
- program/tests/tests/add_remove_validator.rs
- program/tests/tests/limits.rs
- program/tests/tests/merge_stake.rs
- program/tests/tests/mod.rs
- program/tests/tests/solana_assumptions.rs
- program/tests/tests/stake_deposit.rs
- program/tests/tests/unstake.rs
- tests/test_solido.py
Add a seeds for the unstake accounts and change some variables to cope with the modifications.
Changes:
- Split `VALIDATOR_STAKE_ACCOUNT` in `VALIDATOR_STAKE_ACCOUNT` and `VALIDATOR_UNSTAKE_ACCOUNT`.
- Function to split stake accounts `split_stake_account`, so it can be reused in `process_withdraw` and `process_unstake`.
- Bugfix (please check that): the inactive stake calculation at `StakeAccount::from_delegated_account` was subtracted twice, once from the `activating_lamports` and another for the `deactivating_lamports`. In other words, when the stake is being deactivated, the `activating_lamports` is not subtracted.
- New type `SeedRange` that is reused for `stake_seeds` and `unstake_seeds` for the `Validator`'s state.
- Split `find_stake_account_address` into …
> Implement the `Unstake` instruction.

- program/src/error.rs
- program/src/processor.rs
- program/src/state.rs
- program/tests/tests/stake_deposit.rs
Add an additional check in `StakeDeposit` to confirm that no other validator with less stake exists.
* This reduces the power that maintainers have to mess with the stake distribution, which is good because it reduces the amount of trust in them. It is still possible for rogue maintainers to disturb the balance, but not by as much.
* When two maintainers race and produce the same `StakeDeposit` instruction, previously this could lead to one validator having too much stake, but now it will cause one of the two transactions to fail.
This is an alternative to #219, which will be obsolete once this is merged.
> Guard stake deposit

- program/src/instruction.rs
While working on #388 I discovered that we also had unused accounts in `AddValidator`. These were a leftover from back when we used the SPL stake pool, the accounts are no longer referenced.
> Remove unused accounts from `AddValidator`

- program/src/instruction.rs
- program/src/process_management.rs
- program/tests/context.rs
This was reported by Neodyme.
`RemoveValidator` still required a signature from the manager. We forgot to remove this account when we made `RemoveValidator` world-callable in https://github.com/ChorusOne/solido/pull/377. (I [mentioned](https://github.com/ChorusOne/solido/pull/377#discussion_r693012245) it in my first review but then I missed it after edits.)
Also remove program accounts that are not needed, I think these are a leftover from when we still used the SPL stake pool.
> Do not require manager to sign validator removal

- program/src/processor.rs
- program/tests/context.rs
- program/tests/tests/limits.rs
- program/tests/tests/unstake.rs
- program/tests/tests/withdrawals.rs
This fixes an issue discovered by Neodyme, where `process_withdraw` would not consider the unstake account balance when checking that we withdraw from the validator that has the most stake.
Also add a test to catch this. To make the test easier to write, I modified the test context a bit.
> Fix withdraw checks

- program/src/error.rs
- program/src/processor.rs
- program/tests/context.rs
- program/tests/tests/add_remove_validator.rs
- program/tests/tests/collect_validator_fee.rs
- program/tests/tests/merge_stake.rs
- program/tests/tests/solana_assumptions.rs
- program/tests/tests/stake_deposit.rs
- program/tests/tests/unstake.rs
- program/tests/tests/update_exchange_rate.rs
- program/tests/tests/withdraw_inactive_stake.rs
- program/tests/tests/withdrawals.rs
I wanted to put a limit on the number of unstake accounts, to make sure that we don't have so many that `WithdrawInactiveStake` would fail, because we don't merge the unstake accounts.
But while going over this, I noticed some funny things in the amount computations. We should enforce the minimum stake account balance per stake account, not for the validator's overall balance.
Also, when unstaking the full amount from an inactive validator, we should unstake the full stake account, not the full amount, which might be spread over multiple stake accounts. After a merge they should be in a single one and then the difference is not relevant, but still, this was a bit fishy, so fix that.
To do:
> Limit unstake accounts, fix amount computations

- Cargo.lock
- program/Cargo.toml
- program/src/error.rs
@joncinque discovered a few inconsistencies in our error attributes versus variant names.
We were naming the errors the same as the variant anyway. We don't need a crate or boilerplate for that, we can just reuse the `Debug` impl. This prevents the attribute from being out of sync with the name.
The human-friendliness of `LidoError::Display` is not that important because we don't rely on these errors to diagnose errors, we added `msg!` calls everywhere before we return an error to clarify the problem.
> Simplify `LidoError::Display` impl

- program/src/processor.rs
- program/tests/tests/collect_validator_fee.rs
This was an issue caught by @joncinque: in `CollectValidatorFee`, we never checked that the validator was part of Solido. While I don’t believe this would have any negative consequences, we should still check this, especially in case we make a change to `CollectValidatorFee` in the future and we don’t realize that we did not check this.
I also added a regression test, and I wrote the test first to confirm that it would have caught the bug.
> Refuse to collect fees from foreign vote accounts

- cli/src/maintenance.rs
- program/src/balance.rs
As reported by Neodyme:
> `get_target_balance` has a weird API design. Why would you reuse an old target_balance array instead of creating a new one? This is an issue if the input is not all-zero and some validators are disabled, since their will not get overwritten. But because of your sanity-check for total_lamports_distributed this will simply cause an assertion failure. Currently, the only place that uses this function uses an all-zero input
I’m not sure why I went with the mutable argument, returning a vec is nicer indeed, this pull request implements that.
Also, as reported by Neodyme:
> `get_validator_furthest_below_target` can return an inactive validator, even if the inactive validator has a target of 0, if it is the first validator and all other validators have reached their …
> Simplify target balance computations, take unstake accounts into account

- program/src/logic.rs
- program/src/processor.rs
Neodyme pointed out:
> `create_account_overwrite_if_exists` comment is slightly misleading. While it DOES allow creating an account on an address with >0 lamports balance, it does NOT allow overwriting an account which "really" exists (ie has owner or data set). You only use/need it for the first case though, so the code is entirely sane. (except for the options.sign_seeds passed to the transfer instruction, which are unecessary but also don't break anything).
This fixes that.
> Rename misleading account creation method

- cli/src/config.rs
- cli/src/multisig.rs
We are going to onboard 15 validators tomorrow, which will require 15 multisig transactions, plus some to add the maintainers.
Approving those one by one is going to be tedious and error-prone, therefore:
* Add a helper command `multisig approve-batch`, that takes the path to a file that contains transaction addresses, one per line.
* For every transaction, the command:
* Prints it, like `multisig show-transaction` would.
* Asks the user to confirm to approve.
* If the threshold has been reached, asks the user to confirm to execute.
I quickly tested this manually, but it needs better testing with an automated test. Before I do that though, I’m going to add a script for us to also automatically propose these multisig transactions from the validator onboarding form.
This is still very …
> Add subcommand to approve a batch of multisig transactions

- scripts/propose_add_validators.py
- scripts/validator_onboarding.py
- scripts/verify_multisig_transactions.py
- scripts/verify_validator_submissions.py
We need to onboard 15 validators tomorrow. We have their details in a Google Form that we can export as tsv. We have a script to verify the responses (#410). Now there are two more things we need:
* A way for us to easily crease multisig transactions to add these validators.
* A way for multisig members to easily verify that they are approving the right thing.
This pull request adds two scripts that do just that.
I added a "parser" for the form response tsv in #410, extract it into a module so it can be reused.
* `propose_add_validators.py` iterates the validators and creates multisig transactions. It writes the transaction addresses to a file.
* `verify_multisig_transactions.py` takes the the file with transaction addresses, and also the tsv file of form responses, and checks that the …
> Add script to propose multisig transactions for validators, and to verify these transactions

- CHANGELOG.md
I think this is the only thing left blocking the release.
It would be good to get #414 in as well, for the sole reason that we can tell multisig participants to check out `v1.0.0` and the verification scripts will be there.
> Write changelog for v1.0.0

- cli/src/maintenance.rs
- program/src/balance.rs
The maintainer got stuck choosing the validator to stake because not necessarily the furthest from target has less stake. This PR makes the maintainer chose the validator that has less stake for the stake deposit instead of the furthest from the target.
Added a test to check that the validator with the minimum stake got chosen.
Addresses #422
> Make maintainer pick the validator with less stake

- cli/src/daemon.rs
- cli/src/error.rs
- cli/src/maintenance.rs
This makes a few changes to how the maintenance daemon is set up:
* Distinguish between failing to read the on-chain state (which is likely some connectivity problem), and successfully reading the on-chain state, but failing to perform maintenance (possibly because some other transaction raced us).
* The latter error no longer blocks the on-chain state snapshot from being available in the metrics.
* In the case of a connectivity problem, retry with exponential backoff with jitter, instead of retrying at the normal poll interval.
* Don't randomize the poll interval in case of success. This was initially added to break ties when multiple maintainers are running, but we are going to solve that differently with [maintainer duties](https://github.com/ChorusOne/solido/issues/421), so this …
> Refactor maintainer

- cli/src/config.rs
- cli/src/daemon.rs
- cli/src/maintenance.rs
Fixes #421. Depends on #431.
This pull request introduces *maintainer duties* in order to reduce races between maintainers. We break up time into 100-block “duty slices”, and maintainers take turns for “maintainer duty”.
The maintenance daemon will only submit maintenance transactions if it is on duty in the state snapshot that it is inspecting. This way maintainers will not race to perform the same update. To avoid races at the transition, during the last few slots of the duty slice, no maintainer would submit transactions.
There is one complication: if we would only check whether it’s our duty after we polled, we might be unlucky and poll just before and just after our duty slice. This might happen to the next maintainer as well, etc. To prevent this, keep track of the average block …
> Introduce maintainer duties

- cli/src/helpers.rs
- cli/src/maintenance.rs
- cli/src/prometheus.rs
- cli/src/snapshot.rs
Expose the following new Prometheus metrics.
* Withdrawal count and amount. We were already tracking these, but we forgot to expose them.
* Amount of stake on Solana. This allows us to compute the fraction of stake controlled by Lido. Unfortunately it doesn’t appear to be possible to get current amount of active stake, but we can get the amount from the previous epoch from the stake history sysvar.
* Solana epoch, epoch start slot, and slots per epoch. With the start slot, slots per epoch, and the block height that we already had, we can estimate the time left until the next epoch.
For withdrawal stats, also print them in `solido show-solido`, next to the deposit stats.
> Expose withdraw stats, Solana stake, and Solana epoch info in `/metrics`

- cli/src/main.rs
- cli/src/maintenance.rs
- cli/src/prometheus.rs
- cli/src/snapshot.rs
- tests/util.py
**Note**: This description is outdated, see discussion below for the current state of this pull request.
-------
I was running the maintenance daemon to export metrics all day, and I observed the vote credits going *down*. That’s problematic when used with Promtheus's `rate`, because it treats it as a counter restart and suddenly you have double the rate. The vote credits going down should never be possible, the one thing I can think of that would cause this is, is that the RPC node that we queried was following one particular chain where the votes got credited, but then a different fork won out in the end, and so these vote credits were never awarded after all.
If we use commitment level "finalized", this should not happen.
> Be more explicit about using "confirmed" commitment level, wait for confirmation

- cli/src/daemon.rs
- cli/src/maintenance.rs
- program/src/balance.rs
- program/src/token.rs
- tests/test_solido.py
Adds a function in the maintainer to unstake Lamports from validators if there's the need of a rebalance.
There's a threshold (in %) for when to unstake from validators, the conditions for the unstake are:
- If the amount that should be unstaked is above the threshold.
- If there is some validator which needs to be staked and the amount is above the threshold.
- 
As discussed in #427 with @ruuda this PR implements and tests the unstaking logic.
> Unstake active validators

- cli/src/multisig.rs
- tests/test_multisig.py
Bugfix:
* Identifying the `ChangeMultisig` transaction relies on a 8-byte magic number derived from the multisig program module name. When we updated the multisig program, the module name changed, and therefore the magic number changed, so we should have changed this. We did not catch this in tests, because we only tested that we could execute the transaction, not that we could parse its details.
* Add a test to test that we can parse the details, to prevent this in the future.
* Fix the magic number to make the test pass.
Feature:
* Instead of displaying only the new multisig owners and threshold, display a diff, to make it easier to understand what you are approving.
New output:
```console
$ solido --config mainnet.json multisig show-transaction --transaction-address …
```
> Fix parsing of `ChangeMultisig` in `multisig show-transaction`

- anker/src/error.rs
- anker/src/instruction.rs
- anker/src/logic.rs
- anker/src/processor.rs
- anker/src/state.rs
- testlib/src/anker_context.rs
* Add some missing authorization checks, move some others to make them more obvious.
* Don't store derived addresses, in the state, compute them instead.
* Do store the Solido program id in the state, so we don't have to pass it in in transactions (because we never call it).
Please review very carefully!
> Rework authorization checks in Anker program

- Cargo.lock
- Cargo.toml
- anker/tests/tests/deposit.rs
- anker/tests/tests/withdraw.rs
- testlib/src/solido_context.rs
This adds two tests:
* Test that deposit fails if you pass in the wrong reserve. (The bug that we had in Solido v0.5 before the audit, and that we added a regression test for there. We should pro-actively test it here.)
* Test that the program fails if the instance doesn’t live at the right address. For this I modified the `solana-program-test` framework to add the ability to arbitrarily modify accounts, a kind of “god mode” to make it easier to write tests. To use that, override the dependencies so we use our fork instead of the crates.io version.
* Test that withdraw uses the right exchange rate when the stSOL value goes down.
> Add more tests for Anker deposits

- anker/src/state.rs
- anker/tests/tests/amm.rs
- anker/tests/tests/sell_rewards.rs
- testlib/src/anker_context.rs
The stake pool tokens obeyed a strict ordering,
i.e. `token_a` and `token_b` were tied to stSOL and UST. This order is not necessary and removed.
Test swapping tokens with a stake pool created with swapped `token_a` and `token_b`.
Closes #468
> [Anker] Remove ordering restriction for swap tokens.

- cli/src/multisig.rs
So far the only transfers we have done, are wLDO transfers. We see a large number where it is difficult to count the zeros. We can improve this by special-casing wLDO.
Diff of `target/debug/solido --config mainnet.json multisig show-transaction --transaction-address 3ccNd9MxfroqQ9gmaGQFTt1U65yRsUyiJi1oJhGwaz8E` output:
```diff
diff --git before.txt after.txt
index 33d2e851..8d719712 100644
--- before.txt
+++ after.txt
@@ -23,9 +23,9 @@ Instruction:
* GQ3QPrB1RHPRr4Reen772WrMZkHcFM4DL5q44x1BBTFm
signer: true, writable: false
-  This is a Token instruction. It transfers tokens owned by the multisig.
+  This is an SPL token instruction. It transfers tokens.
Token address: HZRCwxP2Vq9PCpPXooayhJ2bxTpo5xfpQrwB1svh332p
From address:  T7VpKriUL68aQAKXFyfG3jJjvPHnxaC95XsjaZKSZ7b
To address: …
```
> Print wLDO transfers more nicely in multisig utility

- anker/src/state.rs
- anker/tests/tests/deposit.rs
- testlib/src/anker_context.rs
On mainnet this will not happen, but in local testing, it might happen that you set up a Solido instance with zero balance (0 SOL, 0 stSOL), and therefore its exchange rate from the balances is undefined. Then if you try to do an Anker deposit in that initial epoch, previously that would fail. This is not a concern on mainnet, but for testing this is annoying, so do allow deposits during the initial epoch, by defining the exchange rate to be 1 stSOL = 1 bSOL, just like Solido defines 1 stSOL =1 SOL if it has zero balance.
> Allow Anker deposits during initial Solido epoch

- CHANGELOG.md
- Cargo.lock
- anker/Cargo.toml
- cli/Cargo.toml
- program/Cargo.toml
- testlib/Cargo.toml
I want to tag v1.2.0 later this week in preparation for the Anker program audit.
> Add preliminary v1.2.0 changelog

- cli/src/anker_state.rs
- cli/src/maintenance.rs
The maintainer pays for these transactions, it doesn't make sense to pay if the amount moved is not much larger than the transaction fee. Especially for Wormhole transfers, which are expensive due to the accounts it allocates.
> Avoid sending/selling small amounts of Anker rewards

- cli/src/commands_anker.rs
- cli/src/commands_multisig.rs
- program/src/processor.rs
- program/src/state.rs
- tests/test_anker.py
This extends the test script to call `solido anker show`, which acts two-fold:
* It tests that `solido anker show` works.
* We can use it in the remainder of the test to confirm that the instance looks as expected.
This is also the final step for #456, so closes #456.
> Add test for `solido anker show`

- cli/src/config.rs
The unused option was a leftover from when we did not have the maintainer duties yet. Also clarify that `--stake-time` is only intended for testing.
> Clarify maintainer CLI options, remove unused option

- cli/src/anker_state.rs
- cli/src/maintenance.rs
- tests/test_anker.py
Extend the Anker test script by:
* Donating 1 stSOL to Anker’s reserve
* Running one maintenance step, which triggers `SellRewards`
* Check that we now have the expected amount of UST in the reserve
> Test Anker `SellRewards` in test script

- cli/src/commands_anker.rs
- cli/src/config.rs
- tests/test_anker.py
- tests/util.py
* Add a new command to the CLI, `solido anker deposit`, to make a deposit. The recipient is the associated token account of the signer, and this account will be created if it doesn’t exist.
* (In hindsight, the `solido deposit` command for Solido deposits can be simplified to not take multiple snapshots, but let’s not do that right now.)
* Use this to extend the Anker test.
> Add `solido anker deposit` command, use it in Anker test

- anker/src/error.rs
- anker/src/lib.rs
- anker/src/processor.rs
- anker/src/state.rs
- anker/tests/tests/sell_rewards.rs
- testlib/src/anker_context.rs
- testlib/src/solido_context.rs
This fixes a critical issue identified by Neodyme: we never checked the program id of the token swap program before calling it with `invoke_signed` in `SellRewards`. An attacker could call `SellRewards` and pass in their own patched version of the token swap program, which would then be able to steal the full stSOL reserve.
* Add a regression test that would have caught the missing check.
* Fix the bug by checking that the token swap program passed in to the call is the owner of the token swap pool stored in the Anker instance. The token swap pool can only be set by the manager, who we trust to set the right pool that is owned by the right token swap program.
* Add an additional check in `SellRewards` that checks that we don’t lose more stSOL than we intended to sell. If the owner check …
> Anker: Check the token swap program id before we call it

- anker/src/processor.rs
- anker/src/state.rs
Adds a version byte for the Anker state in the same way it's done for Solido.
Closes #510
> Add version byte for Anker

- cli/maintainer/src/commands_anker.rs
- cli/maintainer/src/commands_solido.rs
- cli/maintainer/src/config.rs
- tests/test_anker.py
`anker show-authorities` shows Anker's instance public key and authorities associated with it.
This PR is useful so we can set the b_sol mint with the correct mint authority.
Create some tests so we pass the `bSOL` mint as a parameter when creating Anker.
Closes #518
> Test pre existing mint

- cli/listener/src/main.rs
Only answers /metrics if is in the form `hostname:port`/metrics.
Making it internal if we rewrite the public url with `../api/..`
Closes #522
> Make /metrics internal.

- .github/workflows/build.yml
- buildimage.sh
- docker/Dockerfile.dev
The 1.9.9 and 1.10.0 version broke the `solana validator-info publish` command. I didn't investigate much but I think it's related to the wrong number of bytes or lamports when funding the Info account for it to be rent exempt.
In `solana validator-info publish` we could pass `--info-pubkey` with an already funded account owned by the Config program and with sufficient bytes allocated. However, how could we do this from the Solana client tools 😡? Of course we could write some custom function in Solido, but should we? 😬 
I reverted the upgrade to `1.9.9` until some version fixes this issue. We can upgrade to `1.8.16` so it would download the binaries from Solana's repo.
> Upgrade Solana to 1.8.16

- cli/listener/src/main.rs
Limit query for `const QUERY_INTERVAL_OFFSET: usize = 200` from the
beginning of the epoch.
This is done so the exchange rate could be updated in time.
Close #516
> Limit queries

- cli/listener/src/main.rs
As @ruuda pointed out in #515, we shouldn't return an error when no data points are present for calculating the APY. We instead should return a message with 404 status code.
> Return message when no data point could be calculated

- .github/workflows/build.yml
- tests/start_test_validator.py
- Wait 60s instead of 5s for validator to be up.
- Fix solana command to check our own instance for when it's up.
- Kill validator with -9.
- Use different status codes when existing with error.
> Fix CI tests 🤞 

- anker/src/state.rs
- cli/maintainer/src/commands_anker.rs
- tests/test_anker.py
Slice of the new output for a newly created instance:
```
stSOL reserve value:    Undefined; does Solido have nonzero deposits?
UST reserve address:    G3kFufhrZJGQ6jGNYPvLH84M81XH2Y9x9neKHwJxaD4B
UST reserve balance:    0.000000 UST
Historical stSOL price:
Slot 0: 1.000000 UST per stSOL
Slot 0: 1.000000 UST per stSOL
Slot 0: 1.000000 UST per stSOL
Slot 0: 1.000000 UST per stSOL
Slot 0: 1.000000 UST per stSOL
```
(We still have to modify the maintainer to call `FetchPoolPrice`, I’ll do that next if you weren’t looking into it already @enriquefynn.)
> Print historical stSOL prices in `anker show`

- cli/maintainer/src/commands_anker.rs
- cli/maintainer/src/commands_multisig.rs
- cli/maintainer/src/config.rs
- tests/test_anker.py
Show the following Anker instructions:
- ChangeTerraRewardsDestination
- ChangeTokenSwapPool
- ChangeSellRewardsMinBps
Test management functions
> Show Anker instruction that require multisig

- .github/workflows/build.yml
- anker/src/lib.rs
- anker/src/logic.rs
- anker/src/processor.rs
- cli/maintainer/src/anker_state.rs
- cli/maintainer/src/daemon.rs
- cli/maintainer/src/maintenance.rs
- tests/start_test_validator.py
- tests/test_anker.py
- tests/util.py
Call `FetchPoolPrice` inside maintainer if the following conditions are met:
- current slot > 1st slot of next epoch - (`POOL_PRICE_MAX_SAMPLE_AGE + POOL_PRICE_MIN_SAMPLE_DISTANCE`) OR `rewards >= min_rewards_to_sell`
- slots elapsed from the last check > `POOL_PRICE_MIN_SAMPLE_DISTANCE`
> Implement fetch pool price in maintainer

- anker/src/error.rs
- anker/src/processor.rs
- anker/src/state.rs
- anker/tests/tests/sell_rewards.rs
- cli/maintainer/src/maintenance.rs
- tests/test_anker.py
Addresses https://github.com/ChorusOne/solido/pull/511/files#r839805004. Without this, you can put the final fetch in the same transaction as the sale, and sandwich the final sale by sandwiching two additional fetches (so you control 3 of the 5 price samples, so you control the median). With this added check, you need to sandwich one additional fetch before you can sandwich the final sale.
> Enforce minimum distance between last price sample and `SellRewards`

- cli/listener/src/main.rs
If queries are from the past, set the `Expires` header to `now` + 1 year, otherwise, if we are in the same epoch as the query's end slot, we set the `Expires` to the approximate time until the next epoch.
Closes #526
> Add `Expires` header to query response.

- cli/listener/src/lib.rs
In case of a very high epoch number, the computation for `start_slot + QUERY_SLOT_OFFSET` could overflow. This will not occur in practice, and it’s not triggered by a user input. It could only be triggered by a malicious RPC node. Still, we should fix it, if only to unblock the fuzzer for finding other issues.
> Fix overflow in APY daemon discovered by fuzzer

- Cargo.lock
- Cargo.toml
We need to patch all the dependencies from `solana-*`, to make sure we don't mix packages from crates.io and our fork. Without this, `cargo vendor` will complain with an error like this:
```
$ cargo vendor
error: failed to sync
Caused by:
found duplicate version of package `solana-metrics v1.7.8` vendored from two sources:
source 1: registry `crates-io`
source 2: https://github.com/ChorusOne/solana?branch=program-test-178#af358e1a
```
I listed all of these under patches until Cargo stopped complaining.
This is needed in particular to make this work with `buildRustPackage` in Nix, because it relies on `cargo vendor`.
> Make dependencies compatible with "cargo vendor"

- anker/src/processor.rs
- anker/tests/tests/mod.rs
- anker/tests/tests/sell_rewards.rs
- anker/tests/tests/send_rewards.rs
- testlib/src/anker_context.rs
Currently, our maintainer is failing to call `SendRewards` on mainnet:
```
Error while performing maintenance.
Solana RPC client returned an error:
Request:    Some(SendTransaction)
Kind:       RPC response error
Error code: -32002
Message:    Transaction simulation failed: Error processing Instruction 0: Program failed to complete
Reason:     Transaction preflight failure
Error:     
Raw:      InstructionError(0, ProgramFailedToComplete)
Display:  Error processing Instruction 0: Program failed to complete
Logs:      
Program BNVB8pd4coHpY7MVcrtiHLCLst7fyDGzMtPmfJqFAhwj invoke [1]
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
Program log: Instruction: Approve
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2026 of 153383 compute units
Program …
```
> Fix stack overflow in `Anker::SendRewards`

- CHANGELOG.md
- Cargo.lock
- anker/Cargo.toml
- cli/common/Cargo.toml
- cli/listener/Cargo.toml
- cli/listener/fuzz/Cargo.lock
- cli/maintainer/Cargo.toml
- cli/maintainer/src/anker_state.rs
- cli/maintainer/src/daemon.rs
- cli/maintainer/src/maintenance.rs
- program/Cargo.toml
The maintenance daemons are still trying to call `Anker::SendRewards`, and generating an error most of their duty time. It’s not really harmful, but it would be nice if they didn’t error so we can see when there is actually a problem.
We can make this a small 1.3.3 release just for the maintainer daemon, independent of the v2 stuff that @kkonevets is working on. Nobody is required to update, but I would like to update ours.
> Stop calling `Anker::SendRewards` in maintainer

- cli/maintainer/src/maintenance.rs
One of the validators in the last onboarding wave has U+26A1 HIGH VOLTAGE SIGN and U+FE0F VARIATION SELECTOR-16 in its name. In my terminal and also in Grafana in my browser, these render as a lightning bolt using an emoji font.
Also, due to the way we render labels when rendering the metrics, the variation selector turns into the literal text "\u{fe0f}" (so a
backslash and hex between curly brackets, not an U+FE0F itself).
Strip code points from both blocks to fix this.
> Improve validator name sanitizer

- program/src/processor.rs
`process_withdraw` was failing on recent tests, we passed a slice of one element before `&[&[]]` to `invoke_signed`, probably Solido was trying to call a signed instruction with the empty slice as a bump seed, in fact we should have passed an empty slice `&[]` so it just ignores it. `invoke` calls `inkove_signed` with an empty slice.
> Pass empty seeds when withdrawing

- CHANGELOG.md
- Cargo.lock
- anker/Cargo.toml
- cli/common/Cargo.toml
- cli/listener/Cargo.toml
- cli/listener/fuzz/Cargo.lock
- cli/maintainer/Cargo.toml
- program/Cargo.toml
Let’s make a new release with the few small bugfixes for the maintainer.
> Add changelog for 1.3.4
